steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/todo-app:$SHORT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/todo-app:$SHORT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "deploy"
      - "releases"
      - "create"
      - "release-$SHORT_SHA"
      - "--delivery-pipeline"
      - "hello-cloud-deploy"
      - "--region"
      - "us-central1"
      - "--images"
      - "todo-app=gcr.io/$PROJECT_ID/todo-app:$SHORT_SHA"
      - "--target"
      - "hello-cloud-deploy-target-1"
      - "--source"
      - "cloudrun-service.yaml"

images:
  - "gcr.io/$PROJECT_ID/todo-app:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

# Replace YOUR_PIPELINE_NAME and YOUR_TARGET_NAME with your actual Cloud Deploy pipeline and target names.
